// Mock data for License Management

export const licenseStats = {
  activeLicenses: 12,
  totalSeats: 48,
  usedSeats: 42,
  expiringWithin30Days: 2,
  monthlySpend: 2847,
  annualSpend: 34164,
};

export const activeLicenses = [
  {
    id: 1,
    name: "Enterprise Pro",
    type: "enterprise",
    status: "active",
    seats: 25,
    usedSeats: 23,
    price: 1499,
    billingCycle: "monthly",
    startDate: "2024-01-15",
    expiryDate: "2025-01-15",
    autoRenew: true,
    features: [
      "Unlimited test execution",
      "Advanced analytics",
      "Priority support",
      "Custom integrations",
      "SSO authentication",
    ],
  },
  {
    id: 2,
    name: "QA Team",
    type: "team",
    status: "active",
    seats: 15,
    usedSeats: 14,
    price: 599,
    billingCycle: "monthly",
    startDate: "2024-02-01",
    expiryDate: "2025-02-01",
    autoRenew: true,
    features: [
      "5,000 test runs/month",
      "Team collaboration",
      "Email support",
      "Basic analytics",
    ],
  },
  {
    id: 3,
    name: "Developer Tier",
    type: "developer",
    status: "active",
    seats: 5,
    usedSeats: 3,
    price: 299,
    billingCycle: "monthly",
    startDate: "2024-03-10",
    expiryDate: "2024-05-10",
    autoRenew: false,
    features: [
      "1,000 test runs/month",
      "API access",
      "Community support",
    ],
  },
  {
    id: 4,
    name: "Performance Testing",
    type: "addon",
    status: "active",
    seats: 3,
    usedSeats: 2,
    price: 449,
    billingCycle: "monthly",
    startDate: "2024-01-20",
    expiryDate: "2025-01-20",
    autoRenew: true,
    features: [
      "Load testing",
      "Stress testing",
      "Performance reports",
    ],
  },
  {
    id: 5,
    name: "Visual Testing Add-on",
    type: "addon",
    status: "expiring",
    seats: 10,
    usedSeats: 8,
    price: 199,
    billingCycle: "monthly",
    startDate: "2024-03-01",
    expiryDate: "2024-05-01",
    autoRenew: false,
    features: [
      "Visual regression testing",
      "Screenshot comparison",
      "UI testing tools",
    ],
  },
];

export const licenseHistory = [
  {
    id: 101,
    action: "renewed",
    licenseName: "Enterprise Pro",
    date: "2024-01-15",
    amount: 17988,
    billingCycle: "annual",
    invoiceId: "INV-2024-0115",
    status: "paid",
  },
  {
    id: 102,
    action: "purchased",
    licenseName: "QA Team",
    date: "2024-02-01",
    amount: 7188,
    billingCycle: "annual",
    invoiceId: "INV-2024-0201",
    status: "paid",
  },
  {
    id: 103,
    action: "upgraded",
    licenseName: "Developer Tier",
    date: "2024-03-10",
    amount: 299,
    billingCycle: "monthly",
    invoiceId: "INV-2024-0310",
    status: "paid",
  },
  {
    id: 104,
    action: "renewed",
    licenseName: "Performance Testing",
    date: "2024-01-20",
    amount: 5388,
    billingCycle: "annual",
    invoiceId: "INV-2024-0120",
    status: "paid",
  },
  {
    id: 105,
    action: "purchased",
    licenseName: "Visual Testing Add-on",
    date: "2024-03-01",
    amount: 199,
    billingCycle: "monthly",
    invoiceId: "INV-2024-0301",
    status: "paid",
  },
  {
    id: 106,
    action: "refunded",
    licenseName: "Mobile Testing",
    date: "2024-02-15",
    amount: -399,
    billingCycle: "monthly",
    invoiceId: "INV-2024-0215-R",
    status: "refunded",
  },
  {
    id: 107,
    action: "cancelled",
    licenseName: "API Testing Pro",
    date: "2024-01-30",
    amount: 0,
    billingCycle: "monthly",
    invoiceId: "-",
    status: "cancelled",
  },
];

export const availableLicenses = [
  {
    id: "ent_pro",
    name: "Enterprise Pro",
    type: "enterprise",
    description: "Complete platform access with unlimited resources",
    monthlyPrice: 1499,
    annualPrice: 15990,
    seats: { min: 10, max: 100, default: 25 },
    features: [
      "Unlimited test execution",
      "Advanced analytics & reporting",
      "Priority 24/7 support",
      "Custom integrations",
      "SSO & SAML authentication",
      "Dedicated account manager",
      "SLA guarantee",
    ],
    popular: true,
  },
  {
    id: "team",
    name: "QA Team",
    type: "team",
    description: "Perfect for growing QA teams",
    monthlyPrice: 599,
    annualPrice: 6390,
    seats: { min: 5, max: 50, default: 15 },
    features: [
      "5,000 test runs/month",
      "Team collaboration tools",
      "Email support",
      "Basic analytics",
      "Integrations library",
    ],
    popular: false,
  },
  {
    id: "dev",
    name: "Developer Tier",
    type: "developer",
    description: "Essential tools for individual developers",
    monthlyPrice: 299,
    annualPrice: 3190,
    seats: { min: 1, max: 10, default: 5 },
    features: [
      "1,000 test runs/month",
      "API access",
      "Community support",
      "Basic integrations",
    ],
    popular: false,
  },
  {
    id: "perf",
    name: "Performance Testing",
    type: "addon",
    description: "Advanced performance and load testing capabilities",
    monthlyPrice: 449,
    annualPrice: 4790,
    seats: { min: 1, max: 20, default: 3 },
    features: [
      "Load testing up to 10K users",
      "Stress testing",
      "Performance metrics & reports",
      "Real-time monitoring",
    ],
    popular: false,
  },
  {
    id: "visual",
    name: "Visual Testing",
    type: "addon",
    description: "Automated visual regression testing",
    monthlyPrice: 199,
    annualPrice: 2130,
    seats: { min: 1, max: 30, default: 10 },
    features: [
      "Visual regression testing",
      "Screenshot comparison",
      "Cross-browser testing",
      "UI component testing",
    ],
    popular: false,
  },
  {
    id: "mobile",
    name: "Mobile Testing",
    type: "addon",
    description: "Comprehensive mobile app testing",
    monthlyPrice: 399,
    annualPrice: 4270,
    seats: { min: 1, max: 20, default: 5 },
    features: [
      "iOS & Android testing",
      "Real device cloud",
      "App performance testing",
      "Mobile-specific analytics",
    ],
    popular: false,
  },
];

export const paymentMethods = [
  {
    id: 1,
    type: "card",
    brand: "Visa",
    last4: "4242",
    expiryMonth: 12,
    expiryYear: 2026,
    isDefault: true,
  },
  {
    id: 2,
    type: "card",
    brand: "Mastercard",
    last4: "8888",
    expiryMonth: 8,
    expiryYear: 2025,
    isDefault: false,
  },
];

export const usageData = [
  { month: "Oct", tests: 3200, seats: 38 },
  { month: "Nov", tests: 4100, seats: 40 },
  { month: "Dec", tests: 3800, seats: 41 },
  { month: "Jan", tests: 4500, seats: 42 },
  { month: "Feb", tests: 5200, seats: 42 },
  { month: "Mar", tests: 4800, seats: 42 },
];