export const logStats = {
  totalLogs: 45823,
  todayLogs: 3247,
  errors: 127,
  warnings: 423,
  info: 2697,
  avgResponseTime: 245,
};

export const logEntries = [
  {
    id: 1,
    timestamp: "2025-04-28T14:32:18.234Z",
    level: "error",
    source: "API Gateway",
    user: "alex.thompson@m10platform.com",
    message: "Failed to authenticate user: Invalid token signature",
    details: {
      endpoint: "/api/v1/auth/login",
      ip: "192.168.1.105",
      statusCode: 401,
      duration: 156,
    },
    tags: ["authentication", "security"],
  },
  {
    id: 2,
    timestamp: "2025-04-28T14:31:45.123Z",
    level: "warning",
    source: "Test Runner",
    user: "sarah.chen@m10platform.com",
    message: "Test execution exceeded timeout threshold",
    details: {
      testId: "test_1247",
      timeout: 30000,
      actual: 32450,
      browser: "Chrome 122",
    },
    tags: ["performance", "timeout"],
  },
  {
    id: 3,
    timestamp: "2025-04-28T14:31:20.567Z",
    level: "info",
    source: "Database",
    user: "system",
    message: "Database connection pool optimized",
    details: {
      poolSize: 50,
      activeConnections: 12,
      idleConnections: 38,
    },
    tags: ["database", "optimization"],
  },
  {
    id: 4,
    timestamp: "2025-04-28T14:30:55.890Z",
    level: "error",
    source: "File Storage",
    user: "michael.rodriguez@m10platform.com",
    message: "Failed to upload test screenshot: Storage quota exceeded",
    details: {
      fileSize: "2.4MB",
      quota: "100GB",
      used: "99.8GB",
      path: "/screenshots/test_645.png",
    },
    tags: ["storage", "quota"],
  },
  {
    id: 5,
    timestamp: "2025-04-28T14:30:12.345Z",
    level: "info",
    source: "Scheduler",
    user: "system",
    message: "Scheduled test suite executed successfully",
    details: {
      suiteId: "suite_89",
      testsRun: 47,
      passed: 45,
      failed: 2,
      duration: 12450,
    },
    tags: ["scheduler", "automation"],
  },
  {
    id: 6,
    timestamp: "2025-04-28T14:29:38.789Z",
    level: "warning",
    source: "License Manager",
    user: "system",
    message: "License expiring in 15 days",
    details: {
      licenseName: "Visual Testing Add-on",
      expiryDate: "2025-05-13",
      daysRemaining: 15,
      autoRenew: false,
    },
    tags: ["license", "expiration"],
  },
  {
    id: 7,
    timestamp: "2025-04-28T14:29:05.234Z",
    level: "info",
    source: "User Management",
    user: "nina.patel@m10platform.com",
    message: "New user account created",
    details: {
      userId: 48,
      userName: "Tom Brown",
      email: "tom.brown@m10platform.com",
      role: "QA Engineer",
    },
    tags: ["user", "creation"],
  },
  {
    id: 8,
    timestamp: "2025-04-28T14:28:22.678Z",
    level: "error",
    source: "Integration",
    user: "emma.wilson@m10platform.com",
    message: "Slack notification delivery failed",
    details: {
      webhook: "https://hooks.slack.com/services/T00/B00/XXX",
      error: "Connection timeout",
      retryCount: 3,
    },
    tags: ["integration", "notification"],
  },
  {
    id: 9,
    timestamp: "2025-04-28T14:27:45.123Z",
    level: "info",
    source: "API Gateway",
    user: "james.park@m10platform.com",
    message: "Test execution initiated via API",
    details: {
      endpoint: "/api/v1/tests/run",
      testId: "test_1523",
      environment: "staging",
      method: "POST",
    },
    tags: ["api", "test-execution"],
  },
  {
    id: 10,
    timestamp: "2025-04-28T14:27:12.456Z",
    level: "warning",
    source: "Performance Monitor",
    user: "system",
    message: "High CPU usage detected",
    details: {
      cpuUsage: "87%",
      threshold: "80%",
      duration: "5 minutes",
      affectedServices: ["test-runner", "scheduler"],
    },
    tags: ["performance", "monitoring"],
  },
];

export const logLevels = [
  { value: "all", label: "All Levels", color: "#868E96" },
  { value: "error", label: "Error", color: "#FA5252" },
  { value: "warning", label: "Warning", color: "#F59F00" },
  { value: "info", label: "Info", color: "#4263EB" },
  { value: "debug", label: "Debug", color: "#868E96" },
];

export const logSources = [
  "All Sources",
  "API Gateway",
  "Test Runner",
  "Database",
  "File Storage",
  "Scheduler",
  "License Manager",
  "User Management",
  "Integration",
  "Performance Monitor",
  "Security",
];

export const savedReports = [
  {
    id: 1,
    name: "Daily Error Summary",
    description: "All error-level logs from the past 24 hours",
    type: "automated",
    schedule: "Daily at 9:00 AM",
    lastRun: "2025-04-28T09:00:00Z",
    format: "PDF",
    recipients: ["admin@m10platform.com"],
    filters: {
      level: "error",
      timeRange: "24h",
    },
  },
  {
    id: 2,
    name: "Weekly Performance Report",
    description: "Performance metrics and warnings from the past week",
    type: "automated",
    schedule: "Monday at 8:00 AM",
    lastRun: "2025-04-28T08:00:00Z",
    format: "Excel",
    recipients: ["engineering@m10platform.com"],
    filters: {
      level: "warning",
      source: "Performance Monitor",
      timeRange: "7d",
    },
  },
  {
    id: 3,
    name: "API Usage Analysis",
    description: "API endpoint usage and response times",
    type: "manual",
    schedule: "On-demand",
    lastRun: "2025-04-27T15:30:00Z",
    format: "CSV",
    recipients: ["product@m10platform.com"],
    filters: {
      source: "API Gateway",
      timeRange: "30d",
    },
  },
  {
    id: 4,
    name: "Security Audit Log",
    description: "Authentication and authorization events",
    type: "automated",
    schedule: "Daily at 11:00 PM",
    lastRun: "2025-04-27T23:00:00Z",
    format: "PDF",
    recipients: ["security@m10platform.com", "admin@m10platform.com"],
    filters: {
      source: "Security",
      tags: ["authentication", "authorization"],
      timeRange: "24h",
    },
  },
  {
    id: 5,
    name: "Test Execution Summary",
    description: "Test runs, pass rates, and failure analysis",
    type: "automated",
    schedule: "Daily at 6:00 PM",
    lastRun: "2025-04-27T18:00:00Z",
    format: "PDF",
    recipients: ["qa@m10platform.com"],
    filters: {
      source: "Test Runner",
      timeRange: "24h",
    },
  },
];

export const logAnalytics = {
  byLevel: [
    { name: "Error", value: 127, color: "#FA5252" },
    { name: "Warning", value: 423, color: "#F59F00" },
    { name: "Info", value: 2697, color: "#4263EB" },
  ],
  bySource: [
    { name: "API Gateway", value: 892 },
    { name: "Test Runner", value: 734 },
    { name: "Database", value: 512 },
    { name: "Scheduler", value: 389 },
    { name: "Other", value: 720 },
  ],
  timeline: [
    { time: "00:00", errors: 12, warnings: 34, info: 156 },
    { time: "04:00", errors: 8, warnings: 28, info: 142 },
    { time: "08:00", errors: 15, warnings: 45, info: 234 },
    { time: "12:00", errors: 23, warnings: 67, info: 389 },
    { time: "16:00", errors: 19, warnings: 52, info: 312 },
    { time: "20:00", errors: 14, warnings: 38, info: 198 },
  ],
};

export const exportFormats = [
  { value: "json", label: "JSON", icon: "{ }" },
  { value: "csv", label: "CSV", icon: "📊" },
  { value: "excel", label: "Excel", icon: "📗" },
  { value: "pdf", label: "PDF", icon: "📄" },
];

export const timeRanges = [
  { value: "1h", label: "Last Hour" },
  { value: "24h", label: "Last 24 Hours" },
  { value: "7d", label: "Last 7 Days" },
  { value: "30d", label: "Last 30 Days" },
  { value: "custom", label: "Custom Range" },
];