// Mock data for User Management

export const userManagementStats = {
  totalUsers: 48,
  activeUsers: 42,
  inactiveUsers: 6,
  admins: 3,
  qaEngineers: 28,
  developers: 12,
  viewers: 5,
};

export const users = [
  {
    id: 1,
    firstName: "Alex",
    lastName: "Thompson",
    email: "alex.thompson@m10platform.com",
    role: "Senior QA Engineer",
    roleType: "qa",
    department: "Quality Assurance",
    status: "active",
    avatar: "AT",
    color: "#4263EB",
    joinDate: "2023-01-15",
    lastActive: "2 minutes ago",
    testsRun: 1247,
    permissions: ["view_tests", "run_tests", "create_tests", "delete_tests"],
  },
  {
    id: 2,
    firstName: "Sarah",
    lastName: "Chen",
    email: "sarah.chen@m10platform.com",
    role: "Admin",
    roleType: "admin",
    department: "Engineering",
    status: "active",
    avatar: "SC",
    color: "#E64980",
    joinDate: "2022-11-20",
    lastActive: "5 minutes ago",
    testsRun: 892,
    permissions: ["all"],
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Rodriguez",
    email: "michael.rodriguez@m10platform.com",
    role: "QA Engineer",
    roleType: "qa",
    department: "Quality Assurance",
    status: "active",
    avatar: "MR",
    color: "#7048E8",
    joinDate: "2023-03-10",
    lastActive: "1 hour ago",
    testsRun: 645,
    permissions: ["view_tests", "run_tests", "create_tests"],
  },
  {
    id: 4,
    firstName: "Emma",
    lastName: "Wilson",
    email: "emma.wilson@m10platform.com",
    role: "Developer",
    roleType: "developer",
    department: "Engineering",
    status: "active",
    avatar: "EW",
    color: "#0CA678",
    joinDate: "2023-02-05",
    lastActive: "30 minutes ago",
    testsRun: 423,
    permissions: ["view_tests", "run_tests"],
  },
  {
    id: 5,
    firstName: "James",
    lastName: "Park",
    email: "james.park@m10platform.com",
    role: "QA Lead",
    roleType: "qa",
    department: "Quality Assurance",
    status: "active",
    avatar: "JP",
    color: "#F59F00",
    joinDate: "2022-09-18",
    lastActive: "10 minutes ago",
    testsRun: 1523,
    permissions: ["view_tests", "run_tests", "create_tests", "delete_tests", "manage_users"],
  },
  {
    id: 6,
    firstName: "Lisa",
    lastName: "Anderson",
    email: "lisa.anderson@m10platform.com",
    role: "Viewer",
    roleType: "viewer",
    department: "Product",
    status: "active",
    avatar: "LA",
    color: "#ADB5BD",
    joinDate: "2023-05-22",
    lastActive: "2 days ago",
    testsRun: 0,
    permissions: ["view_tests"],
  },
  {
    id: 7,
    firstName: "David",
    lastName: "Kim",
    email: "david.kim@m10platform.com",
    role: "QA Engineer",
    roleType: "qa",
    department: "Quality Assurance",
    status: "inactive",
    avatar: "DK",
    color: "#868E96",
    joinDate: "2023-01-30",
    lastActive: "1 week ago",
    testsRun: 334,
    permissions: ["view_tests", "run_tests", "create_tests"],
  },
  {
    id: 8,
    firstName: "Rachel",
    lastName: "Martinez",
    email: "rachel.martinez@m10platform.com",
    role: "Developer",
    roleType: "developer",
    department: "Engineering",
    status: "active",
    avatar: "RM",
    color: "#0CA678",
    joinDate: "2023-04-12",
    lastActive: "1 hour ago",
    testsRun: 567,
    permissions: ["view_tests", "run_tests"],
  },
  {
    id: 9,
    firstName: "Tom",
    lastName: "Brown",
    email: "tom.brown@m10platform.com",
    role: "Senior QA Engineer",
    roleType: "qa",
    department: "Quality Assurance",
    status: "active",
    avatar: "TB",
    color: "#4263EB",
    joinDate: "2022-12-08",
    lastActive: "15 minutes ago",
    testsRun: 1089,
    permissions: ["view_tests", "run_tests", "create_tests", "delete_tests"],
  },
  {
    id: 10,
    firstName: "Nina",
    lastName: "Patel",
    email: "nina.patel@m10platform.com",
    role: "Admin",
    roleType: "admin",
    department: "Engineering",
    status: "active",
    avatar: "NP",
    color: "#E64980",
    joinDate: "2022-10-15",
    lastActive: "Just now",
    testsRun: 756,
    permissions: ["all"],
  },
];

export const departments = [
  "All Departments",
  "Quality Assurance",
  "Engineering",
  "Product",
  "Operations",
];

export const roleTypes = [
  { value: "all", label: "All Roles", color: "#868E96" },
  { value: "admin", label: "Admin", color: "#E64980" },
  { value: "qa", label: "QA Engineer", color: "#4263EB" },
  { value: "developer", label: "Developer", color: "#0CA678" },
  { value: "viewer", label: "Viewer", color: "#ADB5BD" },
];

export const permissions = [
  { id: "view_tests", label: "View Tests", category: "Tests" },
  { id: "run_tests", label: "Run Tests", category: "Tests" },
  { id: "create_tests", label: "Create Tests", category: "Tests" },
  { id: "delete_tests", label: "Delete Tests", category: "Tests" },
  { id: "manage_users", label: "Manage Users", category: "Users" },
  { id: "manage_settings", label: "Manage Settings", category: "Settings" },
  { id: "view_analytics", label: "View Analytics", category: "Analytics" },
  { id: "export_data", label: "Export Data", category: "Data" },
];